# Generated by Django 6.1.1 on 2026-09-08 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name shown to the rest of the household.', max_length=80)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chores.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning'), ('outdoor', 'Outdoor'), ('shopping', 'Shopping'), ('admin', 'Household admin'), ('other', 'Other')], default='other', max_length=20)),
                ('effort_weight', models.PositiveSmallIntegerField(default=1, help_text='Relative effort on a 1-10 scale. This is the currency fairness is measured in, so it is deliberately coarse — vacuuming might be 3 where taking out the trash is 1.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('frequency', models.CharField(choices=[('once', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Optional. Used for surfacing time cost, not for fairness.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive chores stop generating new occurrences but keep their history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.household')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('household', 'name'), name='unique_chore_name_per_household')],
            },
        ),
    ]
