# Generated by Django 6.1.1 on 2026-09-08 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('overdue', 'Overdue'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Unassigned occurrences are open for anyone to claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_occurrences', to='chores.member')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chores.chore')),
                ('completed_by', models.ForeignKey(blank=True, help_text='Recorded separately from assigned_to: whoever actually did the work earns the fairness credit, even if someone else was assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_occurrences', to='chores.member')),
            ],
            options={
                'ordering': ['due_date', 'chore__name'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='chores_chor_status_d06b57_idx'), models.Index(fields=['assigned_to', 'status'], name='chores_chor_assigne_6f67d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('chore', 'due_date'), name='unique_occurrence_per_chore_per_day')],
            },
        ),
    ]
