# Generated by Django 6.1.1 on 2026-09-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choreoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='chores.member')),
            ],
            options={
                'verbose_name_plural': 'availability',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('member', 'weekday', 'start_time'), name='unique_availability_slot'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_ends_after_it_starts')],
            },
        ),
        migrations.CreateModel(
            name='ChorePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.SmallIntegerField(choices=[(-1, 'Dislikes'), (0, 'Neutral'), (1, 'Likes')], default=0)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='chores.member')),
            ],
            options={
                'ordering': ['member__display_name', 'chore__name'],
                'constraints': [models.UniqueConstraint(fields=('member', 'chore'), name='unique_preference_per_member_chore')],
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_perform', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text='Optional reason, e.g. "allergic to oven cleaner".', max_length=200)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='chores.member')),
            ],
            options={
                'ordering': ['member__display_name', 'chore__name'],
                'constraints': [models.UniqueConstraint(fields=('member', 'chore'), name='unique_skill_per_member_chore')],
            },
        ),
    ]
