# Generated by Django 6.1.1 on 2026-09-08 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_availability_chorepreference_memberskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning'), ('outdoor', 'Outdoor'), ('shopping', 'Shopping'), ('admin', 'Household admin'), ('other', 'Other')], default='other', max_length=20)),
                ('default_effort_weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('default_frequency', models.CharField(choices=[('once', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
