# Generated by Django 6.1.1 on 2026-09-08 08:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_choretemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Share of a full load this member is expected to carry, where 1.00 is a standard share. Lowered for someone working nights or recovering from illness; 0.00 excuses them entirely. This is how plan section 4 'personal circumstances' enters the fairness maths.", max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('2.00'))]),
        ),
    ]
