# Generated by Django 6.1.1 on 2026-09-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_member_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Advance reminder'), (2, 'Due today'), (3, 'Overdue notice'), (4, 'Household nudge'), (5, 'Offered for reassignment')])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='chores.choreoccurrence')),
            ],
            options={
                'ordering': ['occurrence', 'level'],
                'constraints': [models.UniqueConstraint(fields=('occurrence', 'level'), name='unique_escalation_level_per_occurrence')],
            },
        ),
    ]
